### ISSUE TITLE
preventOverflow.boundariesElement modifier not working as understood for scrollParent

### ISSUE THREAD

**Issue by jjenzz** [FezVrasta/react-popper#232]
I'm getting the same issue as https://github.com/FezVrasta/react-popper/issues/72 which was previously closed. I have the latest version of `react-popper` which uses a version of `popper` that is newer than the one mentioned in that issue.

I've also tried passing a reference to the element without luck:
https://codesandbox.io/s/r72vn14znq

I expected that the popper would flip or move to remain in view until the target is out of view. Perhaps I am implementing this incorrectly or misunderstanding how it should behave so feel free to tell me to shuffle along 🙂

**Comment by jjenzz** [comment]
I have tried with Popper.js and react-popper but both behave differenty:

Popper.js: https://codesandbox.io/s/2x0rk3w3or
React Popper: https://codesandbox.io/s/r72vn14znq

I've remove `escapeWithReference` for now to reduce the variables. It seems these above examples should at least be consistent?

**Comment by seancurtis** [comment]
You don't need some of those modifiers. Take a look at this: https://codesandbox.io/s/lxj18m6zw7

You need `positionFixed: true` because that will allow an element to break outside a scrollParent (without using a portal), and then only the `escapeWithReference` modifier for `preventOverflow`. You weren't passing the styles from the render props to the Popper reference element either (that's how popper passes down certain styles).

**Comment by seancurtis** [comment]
If you don't want it to escape, but instead just want to hide it, you need to use the `outOfBoundaries` render prop and do something with the styles, eg use opacity like this: https://codesandbox.io/s/w7n5m153x5

**Comment by jjenzz** [comment]
That is super helpful @seancurtis ... Your `outOfBoundaries` example is exactly what I was trying to achieve. Thank you 🙂
