### ISSUE TITLE
Arrow break positioning

### ISSUE THREAD

**Issue by nicgirault** [FezVrasta/react-popper#275]
### Reproduction demo

https://codesandbox.io/s/9ljo697wzw

### Steps to reproduce the problem

1.  Commenting the arrow div change the positioning of the popper

### What is the expected behavior?

Popper positioning is the same with and without arrow

### What went wrong?

I didn't specify an absolute position for the arrow div.

### Packages versions

- Popper.js: 
- react-popper: 1.3.3

**Comment by dallasnorton** [comment]
I am seeing the same issue. Any investigation or any progress?

**Comment by FezVrasta** [comment]
The arrow component should have `position: absolute`.

https://codesandbox.io/s/61ny1qp3zz

**Comment by dallasnorton** [comment]
I agree, the arrow isn't the direct culprit. Generally with an arrow you use `offset`, I think the real problem is deeper with the positioning and when you have offsets. Investigating further to see if I am just implementing incorrectly or there is something wrong. `computeStyle` shows it takes into account offsets so there is something going on.

**Comment by nicgirault** [comment]
@FezVrasta yes I understood it after a couple of hours of investigation. I would suggest to write this somewhere in the doc. If I'm right it's not written.
